apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: toi-rapids-and-rivers-grapher
  namespace: toi
  labels:
    team: toi
spec:
  groups:
    - name: toi-rapids-and-rivers-grapher
      rules:
        - alert: toi-rapids-and-rivers-grapher
          expr: sum(increase(log_messages_errors{app="toi-rapids-and-rivers-grapher", level="Error"}[10m])) > 0
          for: 1s
          annotations:
            summary: Applikasjonen har logget en error
            action: "https://logs.adeo.no/app/r/s/kbYdS"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-rapids-and-rivers-grapher
          expr: sum(increase(log_messages_errors{app="toi-rapids-and-rivers-grapher", level="Warning"}[10m])) > 3
          for: 1s
          annotations:
            summary: Økning i warnings
            action: "https://logs.adeo.no/app/r/s/kbYdS"
          labels:
            namespace: toi
            severity: warning
